### ISSUE TITLE
Button centeren

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#107]
**Omschrijving:**
Op dit moment hebben we een `<LightButton />` component. Zou het een idee zijn om deze dynamisch gezien te kunnen centeren. Dus `<LightButton center={true} />`. Dat er dan in het component zelf gecentered wordt. Komt regelmatig voor dat we een button willen centeren. Moet dan wel met een parent tag fixen, maar zoiets zou kunnen:

```svelte
{#if center}
 <div class="center-container">
{/if}
  <button>bla bla</button>
{#if center}
  </div>
{/if}

**Comment by iamDistractech** [comment]
Ik vind zelf dat het parent component verantwoordelijk is voor de layout van zijn kinderen. 

Dus als je op een pagina (of ander component) `<LightButton />` neerzet moet je daar ook de CSS het laten centreren, en niet met `<LightButton center={true} />`

**Comment by iamDistractech** [comment]
Kan ik deze sluiten @jochemvogel
