### ISSUE TITLE
Spel paginas offline beschikbaar

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#113]
Branch name: feature/games-offline-available
Part of: #6 
Blocked by: None

**Omschrijving:**

We gaan hier kijken of we alle paginas offline beschikbaar kunnen krijgen door middel van de fetch in de service worker. Wanneer we dit hebben kunnen fixen gaan we kijken of je een pagina kan opslaan via een button klik

**Comment by iamDistractech** [comment]
De offlinepagina is niet van toepassing. Het moet een offline component zijn. Dit kan echter pas getest/gemaakt worden als de fetch etc. van de spellen op de juiste manier is gemaakt.

**Comment by iamDistractech** [comment]
Blocked by: #37
