### ISSUE TITLE
Testen van het kleurcontrast in de zon

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#122]
Branch name: None
Part of: None
Blocked by: None

**Omschrijving:**

Wanneer we een kleuren pallet hebben uitgekozen moeten we deze gaan testen in de zon. In de Jungle is er natuurlijk genoeg zon en daardoor kunnen sommige kleuren dus volledig wegvallen hierin. hopelijk wordt het snel lekker weer..

**Comment by jochemvogel** [comment]
In da zon tip top in orde
