### ISSUE TITLE
Inlog knop creëren in de menu balk 

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#125]
Branch name: None
Part of: #58 , #164 
Blocked by: #58

**Omschrijving:**

Wanneer het Menu is gemaakt moet hier ook een inlog knop opkomen. Dit gaat natuurlijk in samenwerking met de back-end.

**Comment by iamDistractech** [comment]
De link voor login zit al in het menu, alleen wat er achter zit moet nog gelinkt worden. Deze issue wordt daardoor een beetje overbodig
