### ISSUE TITLE
Offline beschikbaar button feedback geven

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#146]
Branch name: None
Part of: #6 
Blocked by: None

**Omschrijving:**

De Offline beschikbaar button moet wat meer feedback krijgen wanneer er een spel pagina offline is opgeslagen. (Toggle?)

**Comment by iamDistractech** [comment]
@RooyyDoe samen met #152 doen in een `redesign` van de detailpagina?

**Comment by iamDistractech** [comment]
Deze heb je al soort van gefixt toch?

**Comment by RooyyDoe** [comment]
Ja, ik pak hem op samen met #152. Wil je ook direct het redesign mee pakken? @iSirThijs

**Comment by RooyyDoe** [comment]
Gaat opgepakt worden in een grotere `task`: Redesign detail pagina
