### ISSUE TITLE
Category updaten naar categorie

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#151]
![image](https://user-images.githubusercontent.com/34123512/120158752-c2d74180-c1f4-11eb-9183-f188e983a7ea.png)

**Comment by jochemvogel** [comment]
Daarnaast even `text-transform: capitalize` aanzetten. Ik maak er een beter bug van straks.

**Comment by RooyyDoe** [comment]
Komt zo uit de API dus moeten we het daar dan niet in het Nederlands zetten? Want, dit is ook zo bij groepen (groups)
