### ISSUE TITLE
Offline button veranderen naar een checkbox

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#152]
Branch name: feature/offline-button-to-checkbox
Part of: #6 
Blocked by: None

**Omschrijving:**

Offline button moet veranderd worden naar een checkbox

**Comment by iamDistractech** [comment]
@RooyyDoe was dit nog relevant? we hebben nu toch een `if` erop? Misschien kunnen we dit meenemen als we de detailpagina gaan 'redesignen'

**Comment by RooyyDoe** [comment]
Gaat gedaan worden in een grotere `task`: Redesign detail pagina
