### ISSUE TITLE
Offline pagina maken wanneer je navigeert naar een spel

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#153]
Branch name: None
Part of: #6 
Blocked by: None

**Omschrijving:**

Wanneer je geen enkel spel hebt opgeslagen en je navigeert naar een van de detail pagina's moet er een offline pagina komen inplaats van de `pagina bestaat niet` pagina

**Comment by iamDistractech** [comment]
Deze moet even wachten tot de nieuwe homepage/ routes gemerged zijn
