### ISSUE TITLE
Logo Junglegym maken

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#178]
Branch name: [Copy the exact name of the branch]
Part of: [Story reference]
Blocked by: [Task reference]

**Omschrijving:**

Er moet een logo worden gemaakt die we kunnen gebruiken in de applicatie

**Comment by jochemvogel** [comment]
https://www.fontspace.com/category/jungle

**Comment by jochemvogel** [comment]
https://www.fontsc.com/font/tag/jungle
