### ISSUE TITLE
Assignee verwijderen en checklist toevoegen aan story template

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#19]
Branch name: `docs/assignee-verwijderen-en-checklist-toevoegen-aan-story-template`
Part of: -
Blocked by: -

**Omschrijving:**
Thijs staat nog als assignee in de story template. Daarnaast een checklist toevoegen (met onder andere: staat alle benodigde informatie erin).

Die checklist kan later nog worden uitgebreid, maar voor nu is die documentatie checkmark voldoende lijkt mij.

**Comment by iamDistractech** [comment]
On it: ik maak ook een specifieke issue template voor documentatie taken.

**Comment by iamDistractech** [comment]
Staat klaar voor review #20
