### ISSUE TITLE
Check of values bestaan bij spellen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#191]
## Expected Behavior

Als niet alles ingevuld is bij de spellen, dan wil je dat dat goed afgehandeld wordt. Dit kun je doen met een if else.

## Current Behavior

`Cannot read property 'group' of undefined`

## Steps to Reproduce

Een spel aanmaken zonder een target Group.

**Comment by iamDistractech** [comment]
Ik denk dat we dit moeten vragen aan de opdrachtgever. Wat zijn verplichte velden bij het invoeren?

**Comment by iamDistractech** [comment]
`game.d.ts` geeft al via de typing aan welke opties `undefined` kunnen zijn, dus daar kan je gewoon gebruik van maken

**Comment by jochemvogel** [comment]
Ik pak dit morgen even op (inclusief terugkoppelen naar opdrachtgever). Dan kan ik in Strapi alle velden required maken.

Aan de andere kant: schijnbaar doet die t gewoon zonder dat er dingen zijn ingevuld. We krijgen geen errors meer als er bijv. geen omschrijving is. Misschien moeten we het daarom ook niet doen. Enkel alles op card requiren (dus: naam, min spelers, category en groep).

@iSirThijs

**Comment by iamDistractech** [comment]
@jochemvogel  kan ik deze sluiten of pakken we dit nog op?
