### ISSUE TITLE
Te lange titel goed afhandelen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#192]
## Expected Behavior

Als er een te lange titel is, wil je deze af kappen. Dit kan bij de input (Strapi) en/of output (Svelte) gedaan worden.

## Current Behavior

![image](https://user-images.githubusercontent.com/34123512/120659082-4cea0900-c486-11eb-8d79-bc24f03384c2.png)

## Steps to Reproduce

Maak een spel met een te lange tekst.

**Comment by iamDistractech** [comment]
Ik wil beargumenteren dat dit in de output/svelte/css gedaan moet worden... De data moet 'netjes' blijven

**Comment by iamDistractech** [comment]
Dit heb ik gefixt in #202 maar moet nog even gecheckt worden als die gemerged is.

**Comment by jochemvogel** [comment]
@iSirThijs Good enough?

![image](https://user-images.githubusercontent.com/34123512/121313654-e55d0f00-c906-11eb-958b-f634d51d3ff9.png)

**Comment by iamDistractech** [comment]
wat mij betreft wel!
