### ISSUE TITLE
Filter op Strapi API werkend krijgen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#206]
Branch name: `feature/filter-op-strapi-api-werkend-krijgen`

**Omschrijving:**
Filter werkt al op de eigen API, maar nog niet op de Strapi API. Data is hetzelfde, dus zullen nog een aantal dingen aangepast moeten worden. Niet zo veel.

**Comment by iamDistractech** [comment]
Dit is niet meer relevant geworden door de APIs te combineren
