### ISSUE TITLE
Games chronologisch ordenen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#207]
Branch name: `feature/games-chronologisch-ordenen`
Blocked by: https://github.com/iSirThijs/jungle-gym-api/issues/9

**Omschrijving:**
Nieuwste komt bovenaan in de lijst

**Comment by iamDistractech** [comment]
@jochemvogel De api stuurt het nu door, let even op dat je wel `updatedAt: string` aan de typing van `Game` toevoegt in `Game.d.ts`
