### ISSUE TITLE
Filteren op categorie werkt niet meer

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#209]
## Expected Behavior

Op het moment dat je filtert op spelsoort, moeten alleen de spellen met die categorie worden getoond.

## Current Behavior

Filter doet helemaal niets.

## Steps to Reproduce

Probeer te filteren met de Jungle Gym API en zie wat er gebeurd.

**Comment by RooyyDoe** [comment]
Wellicht kunnen we hierin direct het filteren op `offline` mee pakken? :)
