### ISSUE TITLE
Geselecteerde categorie filter aanpassen.

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#210]
**Omschrijving:**

Is het niet een idee om `Tikspel -` te doen in plaats van `Categorie -`? Het lijkt mij logischer om het zo te hebben. Of misschien `Categorie: Tikspel -`. Weet niet of het dan weer te lang wordt.

**Comment by jochemvogel** [comment]
![image](https://user-images.githubusercontent.com/34123512/120885449-4c1db800-c5e9-11eb-96d5-c517d4e49498.png)

**Comment by RooyyDoe** [comment]
New issue for future #252
