### ISSUE TITLE
Een plek waar alle favorieten staan.

### ISSUE THREAD

**Issue by sreen020** [iSirThijs/jungle-gym#216]
Branch name: feature/favorieten-pagina
Part of: #3 
Blocked by: None

**Omschrijving:**

Een pagina waar alle favorieten komen te staan. Deze pagina zal beschikbaar zijn wanneer een gebruiker is ingelogd. Ook gaan we er geen favorieten van maken maar `mijn gymles`

**Comment by jochemvogel** [comment]
#262

**Comment by iamDistractech** [comment]
gedaan in #262
