### ISSUE TITLE
Uitgelicht werkend krijgen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#243]
Blocked by: Jochem => Eerst in CMS iets fixen

**Omschrijving:**
Uitgelicht werkt nog niet. Styling moet ook nog wat beter

![image](https://user-images.githubusercontent.com/34123512/121344074-9d001a00-c923-11eb-80eb-d121c983edc6.png)

**Comment by jochemvogel** [comment]
Ik heb nu zowel een `http://jungle-gym-cms.herokuapp.com/uitgelicht-spel` aangemaakt als een `highlighted` key in het bestaande endpoint `http://jungle-gym-cms.herokuapp.com/games`. 

Let op: API van ons werkt nog niet, want dit zit alleen in Strapi.

Denk erover na: welke van de twee gaan we gebruiken?

- Een uitgelicht toggle in elk spel. Als er meer dan 1 highlighted is, dan pakken we de laatste in de array. Het is niet te doen anders

- Een extra endpoint maken /uitgelicht-spel waar het spel staat dat uitgelicht is. Deze wordt op een andere plek geselecteerd.

Allebei de manieren is dus mogelijk. Kijk zelf maar welke van de twee je gebruikt. Vervolgens zal ik de andere verwijderen.

**Comment by jochemvogel** [comment]
![image](https://user-images.githubusercontent.com/34123512/121366347-b3b16b80-c939-11eb-8899-2cd39b9e9b17.png)

**Comment by jochemvogel** [comment]
![image](https://user-images.githubusercontent.com/34123512/121366304-a8f6d680-c939-11eb-9610-f2c61fa76a57.png)

**Comment by iamDistractech** [comment]
Kan je eventueel nog een uitleg in strapi erbij zetten, waarin je zegt dat altijd de laatste uitgelichte spel te zien is?

**Comment by iamDistractech** [comment]
Also, je kan dit eventueel zelf doorvoeren in de jungle-gym api
