### ISSUE TITLE
Snackbar message als offline

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#244]
**Omschrijving:**

We hebben nu die snackbar in de store werkend. Waarom niet een message als je offline bent (stel internet valt weg). Hetzelfde wat betreft weer online gaan

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events
https://github.com/vinayakkulkarni/s-offline
https://levelup.gitconnected.com/detecting-online-offline-in-javascript-1963c4fb81e1

**Comment by jochemvogel** [comment]
Voor als je gaat testen: je moet echt offline. De `offline` knop bij service worker doet niets. Voordat je straks uren bezig bent en denkt dat het niet werkt.

**Comment by iamDistractech** [comment]
Als we zometeen 'mijn gymles' hebben, is het niet meer van belang dat de user dit weet, tenzij hij een handeling wil doen waar internet voor nodig is. (Na feedback van koop), @RooyyDoe  en ik nemen dit dus mee in het maken daarvan :)

**Comment by jochemvogel** [comment]
#262
