### ISSUE TITLE
Verbeteren van het minimum filter

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#245]
Branch name: [Copy the exact name of the branch]
Part of: [Story reference]
Blocked by: [Task reference]

**Omschrijving:**

Moet de UX hiervan niet beter, want ik begreep het niet. En is nooit de fout van de gebruiker.

Ik zou het als volgt gebruiken: ik kies drie als ik een spel wil met minimaal 3 spelers.

Moet je anders niet: beschikbaar aantal spelers hebben ofzo. Snap je m'n punt?

Het is niet heel logisch dat je filtert op minimaal spelers en je krijgt alle spellen tot dat aantal.

Kan aan mij liggen hoor. Maar ik denk dat gebruikers hier een fout gaan maken.

**Comment by iamDistractech** [comment]
Dit was in principe een fout op de API, is nu gefixt. Kun je dat nog even checken ?
