### ISSUE TITLE
Padding bottom spelpagina toevoegen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#266]
## Expected Behavior

Het ziet er zo enorm rustig en lekker uit

## Current Behavior

Hetisnogaleenbeetjetegenelkaar geplakt

## Steps to Reproduce

https://deploy-preview-262--jungle-gym.netlify.app/spellen/kat-en-muis (mobiel)

Eerlijk gezegd is het overal zo 

Ook: https://deploy-preview-262--jungle-gym.netlify.app/spellen

**Comment by iamDistractech** [comment]
[MDN - env()](https://developer.mozilla.org/en-US/docs/Web/CSS/env())
[Designing Websites for iPhone X](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)

Kijk even naar deze twee, hiermee kan je dus de browser helpen met de padding bepalen, zo zorg je ervoor dat bijvoorbeeld in iOS 15 die URL balk niet in de weg zit. Dit is niet Apple specifiek btw `env()` is gewoon een CSS standaard :)
