### ISSUE TITLE
Uitgelicht doorlinken naar de goede pagina

### ISSUE THREAD

**Issue by RooyyDoe** [iSirThijs/jungle-gym#271]
## Expected Behavior

Kat en Muis zou naar de detail pagina van `kat-en-muist` moeten gaan en niet naar het overzicht

## Current Behavior

Gaat naar het spel overzichts scherm

## Steps to Reproduce

href veranderen

**Comment by jochemvogel** [comment]
Wordt toch al gedaan? https://deploy-preview-265--jungle-gym.netlify.app/

**Comment by RooyyDoe** [comment]
Top!
