### ISSUE TITLE
MijnGymles pagina optimaliseren

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#275]
**Omschrijving:**

Heb wat dingen aangepast, waardoor niet alles meer helemaal klopt (qua positie). Wellicht dat iemand dit nog even kan nakijken. Ifjes kloppen misschien niet meer helemaal.

Ik vond het gewoon niet zo mooi en heb wat ([KLEINE](https://deploy-preview-277--jungle-gym.netlify.app/gymles)) dingen aangepast.

**Comment by iamDistractech** [comment]
Je hebt de uitleg weggehaald! Die moest er juist blijven, die hoort bij de onboarding UX..
