### ISSUE TITLE
Kleine letters inloggen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#283]
## Expected Behavior

Je kunt inloggen

## Current Behavior

Gaat fout omdat capitalized is. Kan dit uit? Op mobiel wordt automatisch Johndoe in eerste instantie. UX

**Comment by jochemvogel** [comment]
Misschien een idee om dit server side te doen @iSirThijs ? Dat `Johndoe` ook goed is als je gebruikersnaam `johndoe` is.

**Comment by iamDistractech** [comment]
Lijkt me overbodig op de server te doen. Waarschijnlijk moet er gewoon een attribute aan het tekst veld gegeven worden, waardoor het OS niet meer auto capitalize doet

**Comment by jochemvogel** [comment]
Ha, ik was echt slecht aan het googelen. Thanks
