### ISSUE TITLE
Inloggen werkt niet optimaal

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#292]
## Expected Behavior

Op het moment dat je ingelogd bent, het tab sluit en terug komt, moet je ingelogd zijn. Vervolgens zie je de spellen die jij eerder heb toegevoegd aan **Mijn Gymles**

## Current Behavior

Als je terug komt, ben je nog steeds ingelogd. De spellen zijn alleen weg. Ze staan niet meer in home en ook niet in Mijn Gymles. Als je naar het overzicht gaat, staan ze er nog wel.

## Steps to Reproduce

Download de app op je telefoon. Log in, sla wat op en sluit dan de app af. Als je dan terug komt, zijn de spellen weg

**Comment by jochemvogel** [comment]
#283 Is hier ook onderdeel van.

Het gaat eigenlijk over het inloggen in het algemeen. Er gaat nog te veel fout.

Als je weg gaat en terug komt (en dus nog steeds ingelogd bent), wil je dat de spellen ook nog opgeslagen staan. Nu is dat niet het geval.

Wat je zou kunnen doen, is het volgende: voeg spellen toe aan een account. Op het moment dat iemand weg gaat (en de cache dus eventueel leeg gaat), dan kun je de volgende keer niet meer de spellen gebruiken. Wat je dan wel zou kunnen doen, is dit oplossen door de spellen te fetchen, zodra de gebruiker weer online is.

Dus: if cache leeg => cache alle spellen die de gebruiker in **Mijn Gymles** heeft. De gebruiker merkt daardoor niet dat de spellen weg waren, omdat deze weer ingeladen worden als de gebruiker online komt.

**Comment by jochemvogel** [comment]
Er zijn nog te veel edge cases. Ik raad aan om vanuit dit issue gewoon meerdere issues te maken. Ga er even goed voor zitten en test van alles. Offline inloggen. Met JavaScript uit. Met slecht internet. Noem het maar op. Op die manier zie je wat er allemaal nog niet goed werkt.

**Comment by iamDistractech** [comment]
De enige reden waarom dit niet goed werkt, is omdat de account niet gesynchroniseerd wordt met de api/database. Het inloggen zelf werkt gewoon.

Als iemand opnieuw het tabblad opent is de store leeg(wat klopt). De user wordt al opnieuw opgehaald in de store, als authenticated `true` is. Daar moet dus nog bij komen dat ook de saved games hier weer ingevuld worden vanuit de api. En zodra iemand een spel opslaat, deze ook naar de api wordt gestuurd/gesynchroniseerd.

Inloggen zonder JavaScript is een aparte issue, maar voor zover ik weet is de oplossing daarvan vrij simpel(zolang cookies maar aanstaan)
