### ISSUE TITLE
Zoekopdracht tekst aanpassen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#313]
## Expected Behavior

`Er is gezocht op:`

## Current Behavior

`Er wordt gezocht op:`

## Steps to Reproduce

Zoek in de search bar en kijk naar het bericht dat komt te staan.

**Comment by jochemvogel** [comment]
https://deploy-preview-312--jungle-gym.netlify.app/spellen

**Comment by jochemvogel** [comment]
![image](https://user-images.githubusercontent.com/34123512/122386526-43749c80-cf6e-11eb-90d7-b88a3174c0dc.png)

**Comment by jochemvogel** [comment]
Filters nog uitschakelen als query `search=` is? @RooyyDoe @iSirThijs

**Comment by RooyyDoe** [comment]
Done!
