### ISSUE TITLE
Spellen uit API halen

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#37]
Branch name: `feature/spellen-uit-api-halen`
Part of: #4 
Blocked by: #10 

**Omschrijving:**
Spellen zijn nu nog enigszins hardcoded. Deze kunnen binnenkort uit de API gehaald worden.

Let wel op: dit heeft geen invloed op het testen. Denk dus na of je dit echt wilt of eerst op UI/UX wilt focussen.

**Comment by iamDistractech** [comment]
Overzicht pagina heeft dit nu al door #56 refactor codebase

**Comment by iamDistractech** [comment]
This is geblokkeerd tot dat de API individuele spelen kan sturen via een endpoint

**Comment by iamDistractech** [comment]
De endpoint voor slugs is er, dus deze issue is niet meer geblocked
