### ISSUE TITLE
Documenteren van CSS

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#44]
Part of: -
Documentation for: -

**Omschrijving:**
Discussie voeren over code style in CSS.

`className` of `class-name`. `rem` of `em`. Zo zullen er vast nog wel meer dingen zijn.

Is het handig om dit in een pipeline te zetten? Kan dit voor CSS? Doen we dit alleen tijdens reviews? Even wat regels opzetten, zodat we hetzelfde doen en consistent zijn.

Assignees: @sreen020 @iSirThijs @RooyyDoe @jochemvogel

**Comment by RooyyDoe** [comment]
Volgens mij hebben we hier met ze alle besloten om gebruik te maken van `class-name` en `em` en dit dan ook consistent aan te houden. 

Als dit in de pipeline kan worden gezet lijkt mij dit alleen maar fijn!

**Comment by iamDistractech** [comment]
We hebben dit besloten, maar moet alleen nog gedocumenteerd worden toch?
