### ISSUE TITLE
Menu maken

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#58]
Branch name: -
Part of: -

**Omschrijving:**
Uiteindelijk wil we ook een menu hebben, zodat er door de app genavigeerd kan worden. Figma design zou gebruikt kunnen worden.

**Comment by iamDistractech** [comment]
Onderdeel van #118 ?

**Comment by iamDistractech** [comment]
Ik pak deze op als pakketje met #164 , #125

**Comment by iamDistractech** [comment]
The basis van het menu is verwerkt in #175

**Comment by iamDistractech** [comment]
@RooyyDoe gaat het menu verder stylen
