### ISSUE TITLE
Modal component maken

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#60]
Branch name: -
Part of: -
Blocked by: -

**Omschrijving:**
Er zijn nu een aantal modals. De basis is misschien wel gewoon hetzelfde. Daarom is het handig om een modal component te maken (of meerdere) `src/components/shared/Modal/..` om consistent te blijven

**Comment by jochemvogel** [comment]
Nadat #57 & de filter modal zijn gemerged deze oppakken.

**Comment by iamDistractech** [comment]
Ik heb in #202 een deel geherstructureerd om dit mogelijk te maken, dus je kan deze eventueel na de merge ervan oppakken?

**Comment by iamDistractech** [comment]
@jochemvogel is dit issue nog relevant?
