### ISSUE TITLE
Format toevoegen bij push

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#66]
Branch name: `workflow/format-toevoegen-bij-push`

**Omschrijving:**
Door een 'simpele' `npm run format` zou de code automatisch geformat moeten worden. Kijken of dit ook echt het geval is.

Note: toevoegen aan pipeline is niet praktisch. Kijk naar [Husky](https://javascript.plainenglish.io/how-to-automatically-format-your-code-before-pushing-to-the-remote-server-a5ace1dc2fa7)

**Comment by iamDistractech** [comment]
Ik denk dat we voor nu gewoon lekker zelf moeten bedenken dat we `npm format` doen
