### ISSUE TITLE
Front-end linken naar admin omgeving

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#88]
Branch name: `feature/frontend-linken-naar-admin-omgeving`
Part of: #10 

**Omschrijving:**
Uiteindelijk zal er een admin omgeving zijn. Deze staat in verbinding met de 'normale' frontend door middel van buttons. Echter, deze moeten alleen zichtbaar zijn als de gebruiker een admin is. Deze logica in dit ticket oppakken. Er zijn nog een accounts, maar door middel van een statische **isUserAdmin** variabele kan dit wel gefaket worden.

**Comment by iamDistractech** [comment]
is dit een duplicate van #23 ?

**Comment by jochemvogel** [comment]
@iSirThijs Nee, deze niet. Dit gaat om het linken naar die pagina. Dus zo'n pennetje (edit) of een prullenbak (verwijder). Dit is dus in principe een klein vrij ticket.
