### ISSUE TITLE
Front-end maken voor admin omgeving

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#89]
Branch name: `feature/frontend-maken-voor-admin-omgeving`
Part of: #10 
Blocked by: #21 

**Omschrijving:**
Om spellen toe te voegen, is er een admin omgeving nodig waar deze spellen aangepast kunnen worden. Deze omgeving moet (voor dit ticket) twee dingen doen: een nieuw spel toevoegen en een bestaand spel bewerken.

Bewerken slug kan zijn: `/spel/kat-en-muis/edit`

Toevoegen wordt iets als: `/spel/add-new`

Verwijderen is niet nodig, want dit kan gewoon vanuit het spel zelf.

Het liefst is er ook een lijst met alle spellen, dus denk aan een admin omgeving, zoals `/admin/spellen`. De spellen in deze lijst linken dan naar de specifieke pagina.

Voor deze specifieke dingen moet eerst nog een wireflow/design worden gemaakt. @iSirThijs & @jochemvogel gaan hier mee aan de slag.

**Comment by iamDistractech** [comment]
Wat is de relatie tussen deze task en #24 #23 ?

**Comment by iamDistractech** [comment]
De taak voor de wireflow is #21

**Comment by jochemvogel** [comment]
@iSirThijs Deze is wel duplicated idd. Bedankt.
